services:
  Sauls\Component\Widget\Collection\WidgetCollection:
    public: true
    arguments: [!tagged sauls_widget.widget]

  Sauls\Component\Widget\View\NullView:
    public: false
    tags: ['sauls_widget.view']

  Sauls\Component\Widget\View\StringView:
    public: false
    tags: ['sauls_widget.view']

  Sauls\Component\Widget\View\PhpFileView:
    public: false
    tags: ['sauls_widget.view']

  Sauls\Component\Widget\View\TwigView:
    public: false
    arguments: ['@twig']
    tags: ['sauls_widget.view']

  Sauls\Component\Widget\Collection\ViewCollection:
    public: false
    arguments: [!tagged sauls_widget.view]

  Sauls\Component\Widget\Factory\WidgetFactory:
    public: true
    arguments:
      - '@Sauls\Component\Widget\Collection\WidgetCollection'
      - '@Sauls\Component\Widget\Collection\ViewCollection'

  Sauls\Component\Widget\Factory\WidgetFactoryInterface:
    alias: '@Sauls\Component\Widget\Factory\WidgetFactory'

  Sauls\Component\Widget\Integration\Twig\TwigExtension:
    arguments:
      - '@Sauls\Component\Widget\Factory\WidgetFactory'
    tags:
      - { name: twig.extension }
